ndi-api:
  image:
    tag: bf4a5270ea58d4b229bdf463eed6fc817172fe15
  ingress:
    enabled: true
    hosts:
      - host: api.ndi.bonnal.cloud
        paths:
          - /
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    tls: true
  # ingress:
  #   enabled: true
  #   hosts:
  #     - host: api.ndi.bonnal.cloud
  #       paths:

