ndi-api:
  image:
    tag: 393fd08f4c6b44d6fef310de18ca001060871832
  ingress:
    enabled: true
    hosts:
      - host: api.ndi.bonnal.cloud
        paths:
          - path: /
            pathType: Prefix
  # ingress:
  #   enabled: true
  #   hosts:
  #     - host: api.ndi.bonnal.cloud
  #       paths:
