apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  project: ndi
  source:
    repoURL: https://github.com/ndi-do/infrastructure.git
    targetRevision: HEAD
    path: applications/api/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: ndi