ndi-front:
  image:
    tag: 6b91c12110487a4182e2279cd8a8a54232b07ccc
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: 'true'
    hosts:
      - host: ndi.bonnal.cloud
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ndi.bonnal.cloud-tls
        hosts:
          - ndi.bonnal.cloud
