ndi-front:
  image:
    tag: 044e9c8a860a7dc2e0ec883d42599091a20556fd
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: 'true'
    hosts:
      - host: ndi.bonnal.cloud
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ndi.bonnal.cloud-tls
        hosts:
          - ndi.bonnal.cloud
