ndi-front:
  image:
    tag: d0dc65f862cbbd3a1328abe006039fd176701dfb
  ingress:
    enabled: true
    hosts:
      - host: api.ndi.bonnal.cloud
        paths:
          - path: /
            pathType: Prefix
  # ingress:
  #   enabled: true
  #   hosts:
  #     - host: api.ndi.bonnal.cloud
  #       paths:
